### ISSUE TITLE
Закрой репу

### ISSUE THREAD

**Issue by I-SER-I** [aogavrilov/Backups#1]

**Comment by I-SER-I** [comment]
Или по репе

**Comment by annchous** [comment]
Закрой репу

**Comment by InRedikaWB** [comment]
![image](https://user-images.githubusercontent.com/22368203/99325039-78a8f700-2886-11eb-853f-01476738f464.png)

**Comment by FrediKats** [comment]
![image](https://user-images.githubusercontent.com/22368203/99325093-95ddc580-2886-11eb-94e4-3c719068c8e0.png)

**Comment by aogavrilov** [comment]
Чуваки, если кто захочет скатать, не делайте, реализация лабы кривая и я ее 2 пары не могу сдать, оно вам нада?

**Comment by aogavrilov** [comment]
Но репу закрыл :)
